MKSHELL=/bin/bash

%.SPLITVCF:Q: %.vcf.gz
	echo "[DEBUG] splitting by chromosome the following vcf: $prereq"
	for chromosome in $(tabix --list-chroms $prereq)
	do
		chunk_number=$((chunk_number + 1))
		subtarget="$stem.chunk$chunk_number.vcf.gz"
		echo "[>..] Extracting $chromosome into $subtarget"
		bcftools view $prereq $chromosome | bgzip > $subtarget
	done
