# Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.TreeMix:VQ: %.treemix.frq.gz
	migration_event_1=$(($MIGRATION_EVENT + 1))
	migration_event_2=$(($MIGRATION_EVENT + 2))
	echo "[DEBUG] Running treemix"
	treemix -seed $SEED_TREEMIX \
		-i $prereq \
		-o $target \
		-k $K_VALUE \
		-global \
		-root $ROOT_POP \
		-bootstrap $BOOTSTRAP_VALUE \
		-m $MIGRATION_EVENT \
		-noss \
	&& treemix -i $prereq -m $migration_event_1 -g $target.vertices.gz $target.edges.gz -o $target"_M1" \
	&& treemix -i $prereq -m $migration_event_2 -g $target.vertices.gz $target.edges.gz -o $target"_M2"

%.treemix.frq.gz:Q: %.frq.strat.gz
	echo "[DEBUG] Converting plink files to treemix input"
	python plink2treemix.py $prereq $target

%.frq.strat.gz:Q: %.frq.strat
	echo "[DEBUG] compress $prereq"
	gzip $prereq

%.frq.strat:Q: %.bed
	echo "[DEBUG] Mixing bfile with clusters"
	$PLINK1 --bfile $stem \
		--freq \
		--missing \
		--within $stem.clust \
		--out $stem
