## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.LD.vcf:Q: %.vcf
	echo "[DEBUG] Removing variants in LD"
	bcftools +prune \
		$prereq \
		--max-LD $LD \
    --window $WINDOW \
		--nsites-per-win $N_sites \
	> $target
