MKSHELL=/bin/bash

%.filtered.vcf:Q: %.vcf
	echo "[DEBUG] filtering vcf from $prereq"
	# only biallelic snps with more than a singleton
	# note, this still allows private homozygous variants
	## second pipe replaces missing ID sites with customIDs
	bcftools view \
		-m2 -M2 --types snps \
		--min-ac 2 $prereq \
	| bcftools +fill-tags -- --tags AF,MAF \
	| awk ' BEGIN {FS=OFS="\t"}
		{
			if($3==".")
				$3=$1"_"$2"_"$4"_"$5
			print $0
		}' - > $target
